# Generated by Django 4.2.4 on 2023-08-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
