# Generated by Django 4.2.4 on 2023-08-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
